
services:
    
volumes:
  postgres-data:
    driver: local
    name: postgres-data
  mongodb-data:
    driver: local
    name: mongodb-data
  mongodb-log:
    driver: local
    name: mongodb-log

networks:
  backend:
    driver: bridge
    name: backend
    
  frontend:
    driver: bridge
    name: frontend



