
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGSQL_ROOT_USER}
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB_NAME_DEV}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres
    networks:
      - backend

    
volumes:
  postgres-data:
    driver: local
    name: postgres-data
  mongodb-data:
    driver: local
    name: mongodb-data
  mongodb-log:
    driver: local
    name: mongodb-log

networks:
  backend:
    driver: bridge
    name: backend
    
  frontend:
    driver: bridge
    name: frontend



